Add a container hardening guide
boozallen/sdp-images pull request #35
Opened 2021-10-12 23:41 UTC by CSpicer-BAH

# PR Details

Provides a detailed explanation of the container hardening process undertaken for the containers of the SDP Images repository and affiliate Iron Bank containers.

## Description

Provides a detailed explanation of the container hardening process undertaken for the containers of the SDP Images repository and affiliate Iron Bank containers.

## How Has This Been Tested

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-10-13 21:01 UTC, steven-terrana commented on container-hardening.md
> +
some additional sections might be helpful. 

1. A Repository Structure section that explains the layout of the repository would be good.  i.e., how each directory is a container and each directory has a Dockerfile and Makefile and whatever else.
2. A "How-To" section might be helpful.   just a quick list of commands you use to build images and build the tars and what not.

2021-10-15 03:00 UTC, CSpicer-BAH commented on container-hardening.md
> +    5. Iron Bank will provide a determination if further action is required
Agree, a diagram would probably be helpful here, or at least some visual of what the process is describing. Typing out the specific commands used would probably turn this into a hardening guide for each container. General `How-To's` have been captured however. My plan is that each container will have a section in its README for how to use the container and other specifics for that container, as part of a task to update all the READMEs in this repo.

2021-10-15 17:03 UTC, psig-bah requested changes

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    otherwise login to [repo one](https://repo1.dso.mil/)
consistency: repo one -> Repo One

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    1. Can be located as an excel spreadsheet in the **csv-output** job artifact
consistency: excel -> Excel

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    possible patchs or mitigations for their resolution, most notably
spelling: patchs -> patches & mitigations -> mitigation steps

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    defined in the excel spreadsheet mentioned in step 6
consistency: excel -> Excel

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    1. In the excel spreadsheet described in step 6, provide a written justification
consistency: excel -> Excel

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    3. Select the **Issues** tab in the Iron Bank container repository, and append the justifications to the appropriate issue.
consistency: remove period

2021-10-15 17:03 UTC, psig-bah commented on container-hardening.md
> +    and link the merge request to the corresponding issue.
consistency: remove period

2021-11-17 15:35 UTC, psig-bah commented on container-hardening.md
> +
added a new issue to update the README (#36 ) for the first item

2021-11-17 15:44 UTC, psig-bah commented on container-hardening.md
> +    5. Iron Bank will provide a determination if further action is required
added new issue (#37 ) to track the second item (creating a diagram of the steps/process)

2021-11-17 15:45 UTC, psig-bah approved these changes

2021-11-17 15:47 UTC, merged